import type { ClientContext } from '@citadel/shared';

export function makeTestClient(overrides: Partial<ClientContext> = {}): ClientContext {
  const now = new Date('2026-01-01T00:00:00Z');
  return {
    core: {
      id: 'client_test_1',
      slug: 'test-client',
      companyName: 'Test Client Co',
      legalName: null,
      industry: 'Testing',
      description: 'A fictional business used only in tests.',
      website: 'https://example.com',
      phone: '(208) 555-0142',
      email: 'test@example.com',
      address: null,
      city: "Coeur d'Alene",
      state: 'ID',
      zip: '83814',
      timezone: null,
      status: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    },
    services: [
      {
        id: 'service_test_1',
        clientId: 'client_test_1',
        serviceName: 'Widget Installation',
        description: 'We install widgets.',
        priority: 0,
        active: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    serviceAreas: [
      {
        id: 'area_test_1',
        clientId: 'client_test_1',
        name: "Coeur d'Alene",
        city: "Coeur d'Alene",
        state: 'ID',
        priority: 0,
        active: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    brandProfile: {
      id: 'brand_test_1',
      clientId: 'client_test_1',
      brandVoice: 'Write like a helpful local expert.',
      tone: 'Friendly and direct.',
      preferredPhrases: ['locally owned and operated'],
      forbiddenPhrases: ['best in the world', 'guaranteed for life'],
      writingStyle: null,
      emojiPolicy: null,
      capitalizationPreferences: null,
      ctaPreferences: null,
      otherRules: ['Keep it under 120 words.'],
      createdAt: now,
      updatedAt: now,
    },
    targetAudience: null,
    seoProfile: {
      id: 'seo_test_1',
      clientId: 'client_test_1',
      primaryKeywords: ['widget installation'],
      secondaryKeywords: [],
      targetLocations: [],
      priorityServices: [],
      searchIntent: null,
      competitors: [],
      seoNotes: null,
      createdAt: now,
      updatedAt: now,
    },
    offers: [
      {
        id: 'offer_test_1',
        clientId: 'client_test_1',
        offerName: 'Free Estimate',
        description: 'Free estimate on all new installs.',
        cta: null,
        restrictions: null,
        active: true,
        startDate: null,
        endDate: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    faqs: [],
    marketingNotes: [],
    recentContent: [],
    ...overrides,
  };
}
